
##关闭缓存及时刷新
##spring.freemarker.cache=false
##spring.thymeleaf.cache=true
#
#
##热部署生效
#spring.devtools.restart.enabled=true

spring:
  devtools:
    restart:
      enabled: true
      #设置重启的目录,添加那个目录的文件需要restart
      additional-paths: src/main/java
  freemarker:
    template-loader-path: classpath:/templates #设定ftl文件路径
    cache: false #关闭缓存, 即时刷新, 上线生产环境需要改为true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    #  ############################################################
    #  #
    #  # thymeleaf 静态资源配置
    #  #
    #  ############################################################
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false  # 关闭缓存, 即时刷新, 上线生产环境需要改为true

    #
    #
    #  ############################################################
    #  #
    #  # 配置数据源相关	使用阿里巴巴的 druid 数据源
    #  #
    #  ############################################################
  datasource:
    url: jdbc:mysql://localhost:3306/redisstudy?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  #  ############################################################
  #  #
  #  # REDIS 配置
  #  #
  #  ############################################################
  redis:
    database: 1             # Redis数据库索引（默认为0）
    host: 192.168.160.132   # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: 123456        # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 1000    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10        # 连接池中的最大空闲连接
        min-idle: 2         # 连接池中的最小空闲连接
    timeout: 1000              # 连接超时时间（毫秒）
#  ############################################################
#  #
#  # mybatis 配置
#  #
#  ############################################################
#  # mybatis 配置
mybatis:
  type-aliases-package: com.redis.study.redistudy.pojo
  mapper-locations: classpath:mapper/*.xml
  pagehelper.helperDialect: mysql
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
mapper:
  mappers: com.redis.study.redistudy.utils.MyMapper
  not-empty: false
  identity: MYSQL
#  # 通用 Mapper 配置
#  # 为mybatis设置，生产环境可删除
restart:
  include:
    mapper: /mapper-[\\w-\\.]+jar
    pagehelper: /pagehelper-[\\w-\\.]+jar
#  #排除那个目录的文件不需要restart
#  #spring.devtools.restart.exclude=static/**,public/**
#  #classpath目录下的WEB-INF文件夹内容修改不重启
#  #spring.devtools.restart.exclude=WEB-INF/**
#

#  ############################################################
#  #
#  # 配置i18n 资源文件，供thymeleaf 读取
#  #
#  ############################################################
#spring.messages.basename=i18n/messages
#spring.messages.cache-seconds=3600
#spring.messages.encoding=UTF-8
#
#
#  #设定静态文件路径，js,css等
#spring.mvc.static-path-pattern=/static/**
#
#  ############################################################
#  #
#  # freemarker 静态资源配置
#  #
#  ############################################################

#
#

#  ############################################################
#  #
#  # Server 服务端相关配置
#  #
#  ############################################################
#  # 配置api端口号
#  #server.port=8088
#  # 配置context-path, 一般来说这个配置在正式发布的时候不配置
#  #server.context-path=/IMooc
#  # 错误页，指定发生错误时，跳转的URL --> BasicErrorController
#  #server.error.path=/error
#  # session最大超时时间(分钟)，默认为30分钟
#server.session-timeout=60
#  # 该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败,
#  # 只有特殊需求的情况下才配置, 具体根据各自的业务来设置
#  #server.address=192.168.1.2
#
#  ############################################################
#  # Server - tomcat 相关常用配置
#  ############################################################
#  # tomcat最大线程数, 默认为200
#  #server.tomcat.max-threads=250
#  # tomcat的URI编码
#server.tomcat.uri-encoding=UTF-8
## 存放Tomcat的日志、Dump等文件的临时文件夹，默认为系统的tmp文件夹
##（如：C:\Users\Shanhy\AppData\Local\Temp）
##server.tomcat.basedir=H:/springboot-tomcat-tmp
## 打开Tomcat的Access日志，并可以设置日志格式的方法：
##server.tomcat.access-log-enabled=true
##server.tomcat.access-log-pattern=
## accesslog目录，默认在basedir/logs
##server.tomcat.accesslog.directory=
## 日志文件目录
##logging.path=H:/springboot-tomcat-tmp
## 日志文件名称，默认为spring.log

##logging.file=myapp.log